### ISSUE TITLE
aa tags mixed with ideographic spaces

### ISSUE THREAD

**Issue by boringvipper** [oprel/emanon#2]
## The post:

```
[aa]
(ideographic space)1
2[/aa]
3
```
## produces:

``` html
<span lang="ja"><br>
<p><span lang="ja">(ideographic space)1<br>
2</span><br>
3</span></p>
```

Which is both an html syntax error, and makes 3 a part of the sjis text.
## solutions:

only have the ideographic space mark sjis art when there are no aa tags in the post (easier)
do not have ideographic space recognition inside aa tags (preferred)

**Comment by oprel** [comment]
SJIS art triggered by an ideographic space can be escaped with a double linebreak. I went with your first option, since it makes more sense resourcewise and I doubt people will often mix tag and space induction in one post.

```
 if ($str !~ /\[aa\]/){
        $str =~ s/^@@(\n[^\n])/\x{3000}$1/gm;
        $str =~ s/(^|\n+)(\x{3000}.+?)(\n\n+|\Z)/$1 . '<p><span lang="ja">' . markup_escape($2) . '<\/span><\/p>' . $3/emgs;
        $str =~ s/(<span lang="ja">)\x{3000}\n/$1/g;
    }
```
