### ISSUE TITLE
Site URL regex is broken

### ISSUE THREAD

**Issue by boringvipper** [oprel/emanon#6]
## The post:

```
http://secretareaofvipquality.org/read.cgi/saovq/1438508070/1-100
```
## produces:

``` html
<a href="">→</a>
```
## solution:

Haven't looked into it yet.

**Comment by oprel** [comment]
I haven't looked into what caused this, but it's fixed with the new version of markup.pm

**Comment by boringvipper** [comment]
Nice, it works!
