### ISSUE TITLE
Arbitrary Execution of Javascript

### ISSUE THREAD

**Issue by boringvipper** [oprel/emanon#7]
# The Post

```
[url=YYYhttp://secretareaofvipquality.org/ZZZ<FFF]AAA[/url]
```
# produces

``` html
<a href=
    "http://YYY<a href="
        /ZZZ
    ">&rarr;/ZZZ</a>&lt;FFF"
>AAA</a>
```
# Security Issue

ZZZ can be used to execute javascript, and potentially do other things.

Arbitrary code can be executed like such:

```
[spoiler][url=http://d.o/onmouseover=eval(atob(this.parentNode.nextElementSibling.href.substr(11)))//][/url][/spoiler][url=b.c/YWxlcnQoKQ==][/url]
```

Where YWxlcnQoKQ== is where your base64 encoded code goes.

I couldn't resist playing with it (sorry). I made an [example post](http://secretareaofvipquality.org/read.cgi/saovq/1444128918/10) with it. It activates on hover.
# The problem

The problem must come from the interaction between the url tags and the regex for auto link detection. This is due to your recent update where you moved the auto link detection to the top of the code. The link is first recognized as a stand alone link and is put in an anchor tag. Next, it is wrapped in another anchor tag because of the url bbcode.
# solution:

Revert to an old version of your software. At least for now.
For a long term solution, you can either leave the auto detection url at the bottom, or you can include somewhere in your regex that urls encased in a url tag should not be recognized.

**Comment by oprel** [comment]
I'm glad I was still awake for this. The problem is that I was only scanning the content for anchor tags and forgot to scan the parameter as well. Thank you for the detailed report and for being so vigilant. I'm terribly glad you found this bug before anyone else.

The following code was added and everything works fine:
`$param =~ s/<a.*>|<\/a>//g;`

**Comment by boringvipper** [comment]
Haha, no problem.
